package com.buildwithus.common.enums;

public enum NotificationType {
    NEW_FOLLOWER,
    COLLABORATION_REQUEST,
    COLLABORATION_ACCEPTED,
    COLLABORATION_REJECTED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    TEAM_JOIN_REQUEST,
    TEAM_JOIN_ACCEPTED,
    TEAM_JOIN_REJECTED,
    NEW_BADGE,
    PROJECT_COMMENT,
    SYSTEM
}